[package]
name = "rmatrix"
version = "0.1.0"
authors = ["Lucas Rooyakkers <lucas.rooyakkers@protonmail.com>"]

[dependencies]
rand = "0.3"
clap = "2.28"
chan = "0.1"
ncurses = "5.86.0"
term_size = "0.3"
chan-signal = "0.3"

