[package]
name = "rmatrix"
version = "0.1.0"
authors = ["Lucas Rooyakkers <lucas.rooyakkers@protonmail.com>"]

[dependencies]
rand = "0.3"
chan = "0.1"
structopt = "0.2"
pancurses = "0.13"
term_size = "0.3"
chan-signal = "0.3"
