[package]
name = "r-matrix"
description = "Rust port of cmatrix."
version = "0.2.0"
authors = ["Lucas Rooyakkers <lucas.rooyakkers@protonmail.com>"]
license = 'GPL-3.0-or-later'

[dependencies]
pancurses = "0.16.1"
rand = { version = "0.8.3", features = ["small_rng"] }
signal-hook = { version = "0.3.8", features = ["extended-siginfo"] }
structopt = "0.3.21"
term_size = "0.3.2"
